services:
  postgres:
    image: postgres:15
    container_name: unifconect_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: unifconect
      POSTGRES_PASSWORD: unifconect123
      POSTGRES_DB: unifconect_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unifconect_backend
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://unifconect:unifconect123@postgres:5432/unifconect_db
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  postgres_data:
