FROM node:18-slim AS builder
WORKDIR /usr/app

COPY package*.json ./
COPY prisma/ ./prisma/
RUN npm install
run apt-get update -y && apt-get install -y openssl
COPY . .
RUN npm run build


FROM node:18-slim AS production
run apt-get update -y && apt-get install -y openssl
WORKDIR /usr/app
ENV NODE_ENV=production

COPY --from=builder /usr/app/dist ./dist
COPY --from=builder /usr/app/node_modules ./node_modules
COPY --from=builder /usr/app/prisma ./prisma
COPY package.json ./

EXPOSE 3000
CMD ["node", "dist/server.js"]